### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by sharepointmike** [LRvdLinden/f1_dd_addon#1]
I like this one very much. Is there any way to install it in the Home Assistant CORE version (as this does not have add-inn's available)?

**Comment by LRvdLinden** [comment]
You can use the formulaone api true hacs and google calender intergration. After that rebuild it in lovelace.

**Comment by LRvdLinden** [comment]
![image](https://user-images.githubusercontent.com/77990847/162430797-fd12b321-ca3c-4e87-ac02-020c122856c2.png)
![image](https://user-images.githubusercontent.com/77990847/162430805-be1ecf60-63d4-494a-8cc6-efcac8c631c8.png)

**Comment by sharepointmike** [comment]
What doe you mean by "Rebuild in lovelace"? Where can I find lovelace?

**Comment by sharepointmike** [comment]
Question, how do you get the (weekend) timetable from the api? 
It only exposes:

next_race | The Next race of the current championship season
races | Array of all the races of the current championship season
drivers | Sorted array of all drivers of the current championship season ordered by descending points
constructors | Sorted array of all constructors of the current championship season ordered by descending points

**Comment by sharepointmike** [comment]
Hi @LRvdLinden.  Could you share how to get the weekend timetable. Tried to do some own development this weekend but no luck so far  ;-)
