### ISSUE TITLE
yaml files and maps

### ISSUE THREAD

**Issue by freggel2** [LRvdLinden/f1_dd_addon#2]
I'm confused.

I have done everything described from step 1.
I have the Google Calendar Event integration.
And the revive etc.
Underneath that it says "create sensors"
Copy and place the f1.yamlfile from the folder sensor in to your /config/sensor directory or configuration.yaml <-- I did this too.
Then it says the following:

    Copy the formula1 folder in to the dwains-dashboard/addons/more_page directory.
    Open your more_page.yaml file in dwains-dashboard/configs and add the following;

Now in my www/config should I create a new folder called "dwains-dashboard" and in it another new folder called "addons" and then create another new folder "more_page"?
And then you talk about "open your more_page.yaml file" in "dwains-dasboard/configs"

I don't see a more_page.yaml file at all. And I don't have a dwains-dashboard/configs folder either. There is a page.yaml on your github though

No idea what belongs where and where to "conjure" what from.

**Comment by LRvdLinden** [comment]
It is a build as a addon for Dwains Dashboard what you can install true HACS.

**Comment by freggel2** [comment]
> 
Thank you. That wasn't clear for me.

I will continue.

**Comment by freggel2** [comment]
Just one more question.
The solution you provided me did the trick. I can see all the events now. Thank you so much.

But how or where do I see the track map image?
