### ISSUE TITLE
DD3 

### ISSUE THREAD

**Issue by FaiekA** [LRvdLinden/f1_dd_addon#4]
Hi Thanks for your response on the update to DD3 -  I have a bit of an issue still - error on loading DD
I would assume that the installation instructions stays the same and not using blue print ?

`while scanning a simple key in "/config/dwains-dashboard/configs/more_pages/formula1/page.yaml", line 13, column 1 could not find expected ':' in "/config/dwains-dashboard/configs/more_pages/formula1/page.yaml", line 14, column 1`

If you could please assist 
Much appreciated 
Thanks

**Comment by FaiekA** [comment]
Apologies managed to get it working - had change the path :    
`  path: 'dwains-dashboard/configs/more_pages/formula1/page.yaml'`
Just dont know what i did wrong here got this on the more pages.
![F1](https://user-images.githubusercontent.com/52759676/166899575-159a2c94-2b3f-4c9d-a685-67468fc30e20.PNG)

Thank you

**Comment by LRvdLinden** [comment]
Is it fixt now?

**Comment by LRvdLinden** [comment]
Try the brand new blueprint? https://github.com/dwainscheeren/dwains-dashboard-blueprints/tree/main/page-blueprints/Formula%201

**Comment by FaiekA** [comment]
Ok Thanks - will give it a shot now 
Thanks

**Comment by FaiekA** [comment]
Done - your a star !  - thanks a lot 
Working 100%
Thanks again for a really great page ...

**Comment by LRvdLinden** [comment]
Okay nice! Only circuit image in the api is wrong for this weekend. Iam sorry.
